import 'package:flutter/foundation.dart';

@immutable
class PanoramaTour {
  const PanoramaTour({
    required this.venueId,
    required this.manifestAsset,
    required this.placeholder,
  });
  final String venueId;
  final String manifestAsset; // e.g. 'assets/data/indoor/macquarie-theatre.json'
  final bool placeholder;
}

/// The venue->tour map.
///
/// One entry per official-map legend venue that has real 360° photography.
/// A, B, D, E, H and I are covered; C (Food and drink), F (Sport and Aquatic
/// Centre) and G (Astronomical Observatory) have none yet and correctly have
/// no tour — the picker shows them as "coming soon" rather than inventing one.
///
/// The imagery and manifests are generated by `tools/panorama/build.py`, which
/// records the source photograph behind every scene. Nothing outside the A–I
/// legend ships: the Jim Piper Centre (12 Wally's Walk) panorama is held back
/// because the official map letters no activity there.
abstract final class PanoramaData {
  static const List<PanoramaTour> tours = [
    PanoramaTour(
      venueId: 'macquarie-theatre', // A
      manifestAsset: 'assets/data/indoor/macquarie-theatre.json',
      placeholder: false,
    ),
    PanoramaTour(
      venueId: 'mason-theatre', // B
      manifestAsset: 'assets/data/indoor/mason-theatre.json',
      placeholder: false,
    ),
    PanoramaTour(
      venueId: '14-sir-christopher-ondaatje-avenue', // D
      manifestAsset:
          'assets/data/indoor/14-sir-christopher-ondaatje-avenue.json',
      placeholder: false,
    ),
    PanoramaTour(
      venueId: '1-central-courtyard', // E
      manifestAsset: 'assets/data/indoor/1-central-courtyard.json',
      placeholder: false,
    ),
    PanoramaTour(
      venueId: '11-wallys-walk', // H
      manifestAsset: 'assets/data/indoor/11-wallys-walk.json',
      placeholder: false,
    ),
    PanoramaTour(
      venueId: '17-wallys-walk', // I
      manifestAsset: 'assets/data/indoor/17-wallys-walk.json',
      placeholder: false,
    ),
  ];

  /// Exact lookup — the ONLY way a venueId becomes an asset path.
  static PanoramaTour? tourFor(String venueId) {
    for (final t in tours) {
      if (t.venueId == venueId) return t;
    }
    return null;
  }

  static bool hasTour(String venueId) => tourFor(venueId) != null;
}
