import 'package:flutter/foundation.dart';

@immutable
class PanoramaTour {
  const PanoramaTour({
    required this.venueId,
    required this.manifestAsset,
    required this.placeholder,
  });
  final String venueId;
  final String
  manifestAsset; // e.g. 'assets/data/indoor/macquarie-theatre.json'
  final bool placeholder;
}

/// The venue->tour map.
///
/// One entry per official-map legend venue that has real 360° photography.
/// A, B, D, E, F, G, H and I are covered. C (Food and drink) is the only
/// legend venue without a tour, because no panorama is planned for it — so
/// nothing in the D–I picker reads "coming soon" any more.
///
/// G (Astronomical Observatory / Telescope Park) shipped on 2026-08-31. It had
/// been carried as "coming soon" on the strength of this comment, while two
/// usable 8192×4096 originals sat unused in the source set the whole time.
/// Reading the folder, not the comment, is what found them.
///
/// `gymnasium-road` is the exception to "one entry per legend venue": it is a
/// ROUTE, not a lettered venue — the Solar system walk, running the length of
/// Gymnasium Road from the Central Courtyard to the Telescope Park. It carries
/// no map letter, so it is NOT part of the D–I picker catalogue; the picker
/// surfaces it as a pinned card at the top instead (see
/// `panorama_building_picker.dart`). Seven of its twelve scenes reuse imagery
/// E/F/G already bundle (build.py aliasing), so the walk costs ~9.5 MB, not ~26.
/// (The "Central Courtyard stairs" close-up was dropped as an extra stop on
/// 2026-09-05; it reused E's image, so the bundle is unchanged.)
///
/// The imagery and manifests are generated by `tools/panorama/build.py`, which
/// records the source photograph behind every scene. Nothing outside the A–I
/// legend ships, save the Solar system walk above: the Jim Piper Centre
/// (12 Wally's Walk) panorama is held back because the official map letters no
/// activity there.
abstract final class PanoramaData {
  static const List<PanoramaTour> tours = [
    PanoramaTour(
      venueId: 'macquarie-theatre', // A
      manifestAsset: 'assets/data/indoor/macquarie-theatre.json',
      placeholder: false,
    ),
    PanoramaTour(
      venueId: 'mason-theatre', // B
      manifestAsset: 'assets/data/indoor/mason-theatre.json',
      placeholder: false,
    ),
    PanoramaTour(
      venueId: '14-sir-christopher-ondaatje-avenue', // D
      manifestAsset:
          'assets/data/indoor/14-sir-christopher-ondaatje-avenue.json',
      placeholder: false,
    ),
    PanoramaTour(
      venueId: '1-central-courtyard', // E
      manifestAsset: 'assets/data/indoor/1-central-courtyard.json',
      placeholder: false,
    ),
    PanoramaTour(
      venueId: 'sport-and-aquatic-centre', // F
      manifestAsset: 'assets/data/indoor/sport-and-aquatic-centre.json',
      placeholder: false,
    ),
    PanoramaTour(
      venueId: 'astronomical-observatory', // G
      manifestAsset: 'assets/data/indoor/astronomical-observatory.json',
      placeholder: false,
    ),
    PanoramaTour(
      venueId: '11-wallys-walk', // H
      manifestAsset: 'assets/data/indoor/11-wallys-walk.json',
      placeholder: false,
    ),
    PanoramaTour(
      venueId: '17-wallys-walk', // I
      manifestAsset: 'assets/data/indoor/17-wallys-walk.json',
      placeholder: false,
    ),
    // Solar system walk — a route, not a legend venue (see class doc). Surfaced
    // as a pinned card at the top of the picker, never in the D–I letter list.
    PanoramaTour(
      venueId: 'gymnasium-road',
      manifestAsset: 'assets/data/indoor/gymnasium-road.json',
      placeholder: false,
    ),
  ];

  /// Exact lookup — the ONLY way a venueId becomes an asset path.
  static PanoramaTour? tourFor(String venueId) {
    for (final t in tours) {
      if (t.venueId == venueId) return t;
    }
    return null;
  }

  static bool hasTour(String venueId) => tourFor(venueId) != null;
}
